server:
  port: 8083

spring:
  profiles:
    include:
      - "data-access"
#  main:
#    allow-bean-definition-overriding: true
  security:
    user:
      name: johncena
      password: tuturutu
  application:
    name: chat-client

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /

signature:
  secret: secretText