spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql_db:5433/user_db
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false